#!/bin/bash
set -e
# @generated by docker-package skill
# @skill-version 4

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT_OVERRIDE:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
COMPOSE_FILE="${COMPOSE_FILE_OVERRIDE:-${PROJECT_ROOT}/docker-compose.yml}"
STATE_FILE="${PROJECT_ROOT}/.deploy-image"
CONTAINER_NAME="video-transcript-api"
HEALTH_ATTEMPTS="${HEALTH_ATTEMPTS:-30}"
HEALTH_INTERVAL_SECONDS="${HEALTH_INTERVAL_SECONDS:-2}"
CANDIDATE_TAG="${1:-}"
COMPOSE_MIGRATED=0
DEPLOYMENT_SUCCEEDED=0
CANDIDATE_STARTED=0

restore_legacy_compose() {
  if [[ "${COMPOSE_MIGRATED}" == "1" && -f "${COMPOSE_FILE}.pre-digest.bak" ]]; then
    cp -p "${COMPOSE_FILE}.pre-digest.bak" "${COMPOSE_FILE}"
  fi
}

restore_compose_on_failure() {
  local status=$?
  if [[ "${status}" != "0" && "${DEPLOYMENT_SUCCEEDED}" != "1" ]]; then
    if [[ "${CANDIDATE_STARTED}" == "1" ]] && declare -F rollback_or_fail >/dev/null; then
      rollback_or_fail || true
    else
      restore_legacy_compose
    fi
  fi
  return "${status}"
}
trap restore_compose_on_failure EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

if [[ -z "${CANDIDATE_TAG}" || "${CANDIDATE_TAG}" == *@* || "${CANDIDATE_TAG}" == *:latest ]]; then
  echo "[ERROR] Pass an image with a unique non-latest tag." >&2
  exit 2
fi
last_component="${CANDIDATE_TAG##*/}"
if [[ "${last_component}" != *:* ]]; then
  echo "[ERROR] Pass an image with a unique non-latest tag." >&2
  exit 2
fi

if ! docker info >/dev/null 2>&1; then
  echo "[ERROR] Docker is not available." >&2
  exit 1
fi

mkdir -p "${PROJECT_ROOT}"
exec 9>"${PROJECT_ROOT}/.deploy.lock"
if ! flock -n 9; then
  echo "[ERROR] Another deployment is already running for this project." >&2
  exit 1
fi
if [[ ! -f "${COMPOSE_FILE}" ]]; then
  cp "${SCRIPT_DIR}/docker-compose.deploy.yml" "${COMPOSE_FILE}"
fi
if [[ ! -f "${PROJECT_ROOT}/config/config.jsonc" ]]; then
  echo "[ERROR] Missing ${PROJECT_ROOT}/config/config.jsonc" >&2
  exit 1
fi

# Short env_file syntax works on older Compose v2 releases but requires the
# file to exist. An empty file preserves the previous optional-env behavior.
touch "${PROJECT_ROOT}/.env"

compose_args=(-f "${COMPOSE_FILE}" --project-directory "${PROJECT_ROOT}")
if [[ -f "${PROJECT_ROOT}/.env" ]]; then
  compose_args+=(--env-file "${PROJECT_ROOT}/.env")
fi

compose_cmd() {
  docker compose "${compose_args[@]}" "$@"
}

echo "[1/5] Pulling candidate tag..."
docker pull "${CANDIDATE_TAG}"
CANDIDATE_REPOSITORY="${CANDIDATE_TAG%:*}"
CANDIDATE_DIGEST="$(
  docker image inspect --format '{{range .RepoDigests}}{{println .}}{{end}}' "${CANDIDATE_TAG}" \
    | awk -v repo="${CANDIDATE_REPOSITORY}" \
      'index($0, repo "@sha256:") == 1 {print; exit}'
)"
if [[ -z "${CANDIDATE_DIGEST}" ]]; then
  echo "[ERROR] The registry did not return an immutable digest." >&2
  exit 1
fi

echo "[2/5] Running side-effect-free configuration preflight..."
preflight_env_args=()
if [[ -f "${PROJECT_ROOT}/.env" ]]; then
  preflight_env_args+=(--env-file "${PROJECT_ROOT}/.env")
fi
if ! docker run --rm --entrypoint uv "${preflight_env_args[@]}" \
  -v "${PROJECT_ROOT}/config:/app/config:ro" \
  "${CANDIDATE_DIGEST}" \
  run python main.py --check-config --config /app/config/config.jsonc; then
  echo "[ERROR] Candidate preflight failed; the current service was not restarted." >&2
  exit 1
fi

render_service_image() {
  VIDEO_TRANSCRIPT_IMAGE="${CANDIDATE_DIGEST}" compose_cmd config \
    | awk '
        /^  video-transcript-api:$/ { in_service=1; next }
        in_service && /^    image:/ {
          sub(/^    image:[[:space:]]*/, "")
          gsub(/^"|"$/, "")
          print
          exit
        }
        in_service && /^  [^ ]/ { exit }
      '
}

rendered_image="$(render_service_image)"
if [[ "${rendered_image}" != "${CANDIDATE_DIGEST}" ]]; then
  if [[ -n "${COMPOSE_FILE_OVERRIDE:-}" ]]; then
    echo "[ERROR] ${COMPOSE_FILE} does not render the candidate digest." >&2
    exit 1
  fi
  echo "[MIGRATE] Replacing incompatible compose file; backup saved."
  cp -p "${COMPOSE_FILE}" "${COMPOSE_FILE}.pre-digest.bak"
  cp "${SCRIPT_DIR}/docker-compose.deploy.yml" "${COMPOSE_FILE}"
  COMPOSE_MIGRATED=1
  rendered_image="$(render_service_image)"
  if [[ "${rendered_image}" != "${CANDIDATE_DIGEST}" ]]; then
    echo "[ERROR] Migrated compose file does not render the candidate digest." >&2
    exit 1
  fi
fi

compose_container_ref() {
  local container_id
  # `ps -q` still has to load the compose model, so it needs a value for the
  # mandatory ${VIDEO_TRANSCRIPT_IMAGE:?...} interpolation in the compose
  # file even though the image value itself is irrelevant here -- Compose
  # matches the running container by project/service labels, not by image.
  # CANDIDATE_DIGEST is always populated by the time this function can run.
  container_id="$(
    VIDEO_TRANSCRIPT_IMAGE="${CANDIDATE_DIGEST:-unused}" compose_cmd ps -q video-transcript-api 2>/dev/null || true
  )"
  # Falls back to the hardcoded name when Compose can't resolve a container
  # (e.g. it doesn't exist yet). This fallback is only correct because both
  # docker-compose.deploy.yml and docker-compose.image-override.yml pin
  # `container_name: video-transcript-api` -- keep CONTAINER_NAME in sync if
  # either template's container_name ever changes.
  printf '%s\n' "${container_id:-${CONTAINER_NAME}}"
}

OLD_DIGEST=""
if [[ -f "${STATE_FILE}" ]]; then
  OLD_DIGEST="$(tr -d '[:space:]' < "${STATE_FILE}")"
  if [[ ! "${OLD_DIGEST}" =~ @sha256:[0-9a-f]{64}$ ]]; then
    echo "[ERROR] Invalid previous deployment digest in ${STATE_FILE}." >&2
    exit 1
  fi
else
  current_container="$(compose_container_ref)"
  discovered_old="$(
    docker inspect --format='{{.Config.Image}}' "${current_container}" 2>/dev/null || true
  )"
  if [[ "${discovered_old}" =~ @sha256:[0-9a-f]{64}$ ]]; then
    OLD_DIGEST="${discovered_old}"
  else
    old_image_id="$(
      docker inspect --format='{{.Image}}' "${current_container}" 2>/dev/null || true
    )"
    if [[ -n "${old_image_id}" ]]; then
      old_repository="${discovered_old%:*}"
      if [[ -z "${discovered_old}" || "${old_repository}" == "${discovered_old}" ]]; then
        old_repository="${CANDIDATE_REPOSITORY}"
      fi
      OLD_DIGEST="$(
        docker image inspect --format '{{range .RepoDigests}}{{println .}}{{end}}' "${old_image_id}" 2>/dev/null \
          | awk -v repo="${old_repository}" \
            'index($0, repo "@sha256:") == 1 {print; exit}'
      )"
    fi
  fi
fi

deploy_digest() {
  local digest="$1"
  # Mark the candidate before Compose starts. Rolling back before a container
  # is actually replaced is harmless; marking after `up` leaves a signal race.
  CANDIDATE_STARTED=1
  if ! VIDEO_TRANSCRIPT_IMAGE="${digest}" compose_cmd \
    up -d --no-build video-transcript-api; then
    return 1
  fi
}

deploy_legacy_digest() {
  local digest="$1"
  VIDEO_TRANSCRIPT_IMAGE="${digest}" compose_cmd \
    -f "${SCRIPT_DIR}/docker-compose.image-override.yml" \
    up -d --no-build video-transcript-api
}

wait_for_health() {
  local attempt status container_ref
  for ((attempt = 1; attempt <= HEALTH_ATTEMPTS; attempt++)); do
    container_ref="$(compose_container_ref)"
    status="$(docker inspect --format='{{.State.Health.Status}}' "${container_ref}" 2>/dev/null || true)"
    if [[ "${status}" == "healthy" ]]; then
      return 0
    fi
    if [[ "${status}" == "unhealthy" ]]; then
      return 1
    fi
    # Images built before the hardened Dockerfile may have no HEALTHCHECK.
    # Verify the same in-container API endpoint instead of treating the
    # missing Docker health state as a failed rollback.
    if [[ -z "${status}" ]] && docker exec "${container_ref}" python -c \
      "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/livez', timeout=2).read()" \
      >/dev/null 2>&1; then
      return 0
    fi
    sleep "${HEALTH_INTERVAL_SECONDS}"
  done
  return 1
}

rollback_or_fail() {
  # Prevent the EXIT trap from attempting the same rollback a second time.
  CANDIDATE_STARTED=0
  if [[ -z "${OLD_DIGEST}" ]]; then
    echo "[ERROR] No previous digest is available for rollback." >&2
    # Same interpolation requirement as compose_container_ref(): without a
    # value for VIDEO_TRANSCRIPT_IMAGE, Compose refuses to load the model and
    # `stop` fails outright -- which the old `|| true` swallowed silently,
    # leaving the unhealthy candidate running under `restart:
    # unless-stopped`. The image value itself doesn't matter for `stop`.
    VIDEO_TRANSCRIPT_IMAGE="${CANDIDATE_DIGEST:-unused}" compose_cmd stop video-transcript-api || true
    return 1
  fi
  echo "[ROLLBACK] Restoring previous digest..."
  restore_legacy_compose
  if ! deploy_legacy_digest "${OLD_DIGEST}"; then
    echo "[ERROR] Rollback digest failed to start." >&2
    return 1
  fi
  if ! wait_for_health; then
    echo "[ERROR] Rollback digest also failed its health check." >&2
    return 1
  fi
}

echo "[3/5] Starting candidate digest..."
if ! deploy_digest "${CANDIDATE_DIGEST}"; then
  echo "[ERROR] Candidate start failed." >&2
  rollback_or_fail
  exit 1
fi

echo "[4/5] Waiting for candidate health..."
if ! wait_for_health; then
  echo "[ERROR] Candidate health check failed." >&2
  rollback_or_fail
  exit 1
fi

# The state rename and success flag form one tiny critical section. Ignore
# termination only across these local operations so service and state cannot
# commit opposite versions.
trap '' INT TERM
if ! printf '%s\n' "${CANDIDATE_DIGEST}" > "${STATE_FILE}.tmp" || \
   ! mv "${STATE_FILE}.tmp" "${STATE_FILE}"; then
  trap 'exit 130' INT
  trap 'exit 143' TERM
  echo "[ERROR] Failed to commit deployment state; rolling back candidate." >&2
  rm -f "${STATE_FILE}.tmp"
  rollback_or_fail
  exit 1
fi
DEPLOYMENT_SUCCEEDED=1
trap 'exit 130' INT
trap 'exit 143' TERM
echo "[5/5] Deployment complete: ${CANDIDATE_DIGEST}"
