#!/bin/bash
set -e
# @generated by docker-package skill
# @skill-version 4

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REGISTRY_IMAGE="ghcr.io/zj1123581321/video-transcript-api"
GIT_SHA="$(git -C "${PROJECT_ROOT}" rev-parse --short=12 HEAD 2>/dev/null || true)"

if [[ ! "${GIT_SHA}" =~ ^[0-9a-f]{12}$ ]]; then
  echo "[ERROR] A 12-character git SHA is required." >&2
  exit 1
fi
if [[ -n "$(git -C "${PROJECT_ROOT}" status --porcelain --untracked-files=normal)" ]]; then
  echo "[ERROR] Refusing to build from a dirty worktree." >&2
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo "[ERROR] Docker is not available." >&2
  exit 1
fi

IMAGE_REF="${REGISTRY_IMAGE}:${GIT_SHA}"
echo "[1/2] Building ${IMAGE_REF}..."
docker build \
  --build-arg "GIT_SHA=${GIT_SHA}" \
  -f "${SCRIPT_DIR}/Dockerfile" \
  -t "${IMAGE_REF}" \
  "${PROJECT_ROOT}"

echo "[2/2] Pushing ${IMAGE_REF}..."
docker push "${IMAGE_REF}"
echo "Deploy with: ${SCRIPT_DIR}/pull_and_deploy.sh ${IMAGE_REF}"
